/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
/**
 *
 * @author User
 */
public class databuku extends javax.swing.JFrame {
    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    /**
     * Creates new form databuku
     */
    public databuku() {
        initComponents();
        table_databuku();
    }
    protected void aktif() {
        txtkodebuku.setEnabled(true);
        txtjudulbuku.setEnabled(true);
        txtmapel.setEnabled(true);
    }
    protected void kosong() {
        txtkodebuku.setText("");
        txtjudulbuku.setText("");
        txtmapel.setText("");
        rbpaket.setSelected(true);
        rbsmt1.setSelected(true);
    }
    protected void table_databuku() {
        Object[] Baris = {"Kode Buku", "Judul Buku", "Mata Pelajaran", "Tipe Buku", "Semester"};
        tabmode = new DefaultTableModel(null, Baris);
        tabledatabuku.setModel(tabmode);
        String sql = "SELECT * FROM databuku";
        
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet tablebuku = stat.executeQuery(sql);
            while(tablebuku.next()) {
                String kode = tablebuku.getString("kode_buku");
                String judul = tablebuku.getString("judul_buku");
                String mapel = tablebuku.getString("mata_pelajaran");
                String tipebuku = tablebuku.getString("tipe_buku");
                String semester = tablebuku.getString("semester");
                
                String[] data = {kode, judul, mapel, tipebuku, semester};
                tabmode.addRow(data);
            }
            
        } catch (Exception e) {
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        kode_buku = new javax.swing.JLabel();
        judul_buku = new javax.swing.JLabel();
        mata_pelajaran = new javax.swing.JLabel();
        semester = new javax.swing.JLabel();
        txtkodebuku = new javax.swing.JTextField();
        txtjudulbuku = new javax.swing.JTextField();
        txtmapel = new javax.swing.JTextField();
        rbsmt1 = new javax.swing.JRadioButton();
        rbsmt2 = new javax.swing.JRadioButton();
        btnsimpan = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btnbersihkan = new javax.swing.JButton();
        tipe_buku = new javax.swing.JLabel();
        rbpaket = new javax.swing.JRadioButton();
        rblks = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabledatabuku = new javax.swing.JTable();
        btnhapus = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        data_siswa = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        data_guru = new javax.swing.JMenu();
        biaya = new javax.swing.JMenu();
        biaya_spp = new javax.swing.JMenuItem();
        biaya_buku = new javax.swing.JMenuItem();
        biaya_seragam = new javax.swing.JMenuItem();
        biaya_gedung = new javax.swing.JMenuItem();
        transaksi = new javax.swing.JMenu();
        laporan = new javax.swing.JMenu();
        data_admin = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel1.setText("Data Buku");

        kode_buku.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        kode_buku.setText("Kode Buku");

        judul_buku.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        judul_buku.setText("Judul Buku");

        mata_pelajaran.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        mata_pelajaran.setText("Mata Pelajaran");

        semester.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        semester.setText("Semester");

        txtkodebuku.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N

        txtjudulbuku.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N

        txtmapel.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N

        rbsmt1.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        rbsmt1.setText("1");
        rbsmt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbsmt1MouseClicked(evt);
            }
        });

        rbsmt2.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        rbsmt2.setText("2");
        rbsmt2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbsmt2MouseClicked(evt);
            }
        });

        btnsimpan.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnedit.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnedit.setText("Edit");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnbersihkan.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnbersihkan.setText("Bersihkan");
        btnbersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbersihkanActionPerformed(evt);
            }
        });

        tipe_buku.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        tipe_buku.setText("Tipe Buku");

        rbpaket.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        rbpaket.setText("Paket");
        rbpaket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbpaketMouseClicked(evt);
            }
        });

        rblks.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        rblks.setText("LKS");
        rblks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rblksMouseClicked(evt);
            }
        });
        rblks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rblksActionPerformed(evt);
            }
        });

        tabledatabuku.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        tabledatabuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tabledatabuku.setRowHeight(25);
        tabledatabuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabledatabukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabledatabuku);

        btnhapus.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        jMenuBar1.setAlignmentX(1.0F);
        jMenuBar1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        data_siswa.setText("Data Siswa");
        data_siswa.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        data_siswa.setMargin(new java.awt.Insets(0, 5, 0, 5));
        jMenuBar1.add(data_siswa);

        jMenu1.setText("Data Buku");
        jMenu1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jMenu1.setMargin(new java.awt.Insets(0, 5, 0, 5));
        jMenuBar1.add(jMenu1);

        data_guru.setText("Data Guru");
        data_guru.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        data_guru.setMargin(new java.awt.Insets(0, 5, 0, 5));
        jMenuBar1.add(data_guru);

        biaya.setText("Biaya");
        biaya.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        biaya.setMargin(new java.awt.Insets(0, 5, 0, 5));

        biaya_spp.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        biaya_spp.setText("Biaya SPP");
        biaya_spp.setMargin(new java.awt.Insets(4, 0, 4, 0));
        biaya.add(biaya_spp);

        biaya_buku.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        biaya_buku.setText("Biaya Buku");
        biaya_buku.setMargin(new java.awt.Insets(4, 0, 4, 0));
        biaya.add(biaya_buku);

        biaya_seragam.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        biaya_seragam.setText("Biaya Seragam");
        biaya_seragam.setMargin(new java.awt.Insets(4, 0, 4, 0));
        biaya.add(biaya_seragam);

        biaya_gedung.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        biaya_gedung.setText("Biaya Gedung");
        biaya_gedung.setMargin(new java.awt.Insets(4, 0, 4, 0));
        biaya.add(biaya_gedung);

        jMenuBar1.add(biaya);

        transaksi.setText("Transaksi");
        transaksi.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        transaksi.setMargin(new java.awt.Insets(0, 5, 0, 5));
        jMenuBar1.add(transaksi);

        laporan.setText("Laporan");
        laporan.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        laporan.setMargin(new java.awt.Insets(0, 5, 0, 5));
        jMenuBar1.add(laporan);

        data_admin.setText("Data Admin TU");
        data_admin.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        data_admin.setMargin(new java.awt.Insets(0, 5, 0, 5));
        jMenuBar1.add(data_admin);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kode_buku)
                            .addComponent(judul_buku)
                            .addComponent(mata_pelajaran)
                            .addComponent(semester)
                            .addComponent(tipe_buku))
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnbersihkan, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbpaket)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rblks))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbsmt1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbsmt2))
                                    .addComponent(txtmapel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtjudulbuku, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtkodebuku, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kode_buku)
                            .addComponent(txtkodebuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(judul_buku)
                            .addComponent(txtjudulbuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mata_pelajaran)
                            .addComponent(txtmapel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tipe_buku)
                            .addComponent(rbpaket)
                            .addComponent(rblks))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(semester)
                            .addComponent(rbsmt1)
                            .addComponent(rbsmt2)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbersihkan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        String sql = "INSERT INTO databuku VALUES (?, ?, ?, ?, ?)";
        
        try {
            PreparedStatement databuku = conn.prepareStatement(sql);
            databuku.setString(1, txtkodebuku.getText());
            databuku.setString(2, txtjudulbuku.getText());
            databuku.setString(3, txtmapel.getText());
            
            String tipe = "";
            if(rbpaket.isSelected()) tipe = "Paket";
            else tipe = "LKS";
            databuku.setString(4, tipe);
            
            String smstr = "";
            if(rbsmt1.isSelected()) smstr = "1";
            else smstr = "2";
            databuku.setString(5, smstr);
            
            databuku.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Buku Berhasil Disimpan");
            kosong();
            txtkodebuku.requestFocus();
            table_databuku();
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal Menambahkan Data Buku" +e);
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void rbpaketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbpaketMouseClicked
        // TODO add your handling code here:
        if(rbpaket.isSelected())
            rblks.setSelected(false);
    }//GEN-LAST:event_rbpaketMouseClicked

    private void rblksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rblksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rblksActionPerformed

    private void rblksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rblksMouseClicked
        // TODO add your handling code here:
        if(rblks.isSelected())
            rbpaket.setSelected(false);
    }//GEN-LAST:event_rblksMouseClicked

    private void rbsmt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbsmt1MouseClicked
        // TODO add your handling code here:
        if(rbsmt1.isSelected())
            rbsmt2.setSelected(false);
    }//GEN-LAST:event_rbsmt1MouseClicked

    private void rbsmt2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbsmt2MouseClicked
        // TODO add your handling code here:
        if(rbsmt2.isSelected())
            rbsmt1.setSelected(false);
    }//GEN-LAST:event_rbsmt2MouseClicked

    private void tabledatabukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabledatabukuMouseClicked
        // TODO add your handling code here:
        int bar = tabledatabuku.getSelectedRow();
        String kodebuku = tabmode.getValueAt(bar, 0).toString();
        String judulbuku = tabmode.getValueAt(bar, 1).toString();
        String mapel = tabmode.getValueAt(bar, 2).toString();
        String tipebuku = tabmode.getValueAt(bar, 3).toString();
        String semester = tabmode.getValueAt(bar, 4).toString();
        
        txtkodebuku.setText(kodebuku);
        txtkodebuku.setEditable(false);
        
        txtjudulbuku.setText(judulbuku);
        txtmapel.setText(mapel);
        
        if(tipebuku.equals("Paket")) {
            rbpaket.setSelected(true); 
            rblks.setSelected(false);
        } else {
            rbpaket.setSelected(false); 
            rblks.setSelected(true);
        }
        
        if(semester.equals("1")) {
            rbsmt1.setSelected(true); 
            rbsmt2.setSelected(false);
        } else {
            rbsmt1.setSelected(false); 
            rbsmt2.setSelected(true);
        }
        
    }//GEN-LAST:event_tabledatabukuMouseClicked

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "UPDATE databuku SET judul_buku=?, mata_pelajaran=?, tipe_buku=?, semester=? WHERE kode_buku=?";
            PreparedStatement stat = conn.prepareStatement(sql);
            
            stat.setString(1, txtjudulbuku.getText());
            stat.setString(2, txtmapel.getText());
            
            String tipebuku="";
            if(rbpaket.isSelected()) tipebuku="Paket";
            else tipebuku = "LKS";
            stat.setString(3, tipebuku);
            
            String semester="";
            if(rbsmt1.isSelected()) semester="1";
            else semester = "2";
            stat.setString(4, semester);
            stat.setString(5, txtkodebuku.getText());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Buku Berhasil Diubah");
            kosong();
            txtkodebuku.requestFocus();
            table_databuku();
            
            
        } catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Data Buku Gagal Diubah"+e);
        }
    }//GEN-LAST:event_btneditActionPerformed

    private void btnbersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbersihkanActionPerformed
        // TODO add your handling code here:
        kosong();
    }//GEN-LAST:event_btnbersihkanActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null, "Hapus", "Konfirmasi Dialog", JOptionPane.YES_NO_CANCEL_OPTION);
        if (ok == 0 ) {
            String sql = "DELETE FROM databuku WHERE kode_buku='"+txtkodebuku.getText()+"'";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Buku Berhasil Dihapus");
                kosong();
                txtkodebuku.requestFocus();
                table_databuku();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Data Buku Gagal Dihapus"+e);
            }
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(databuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(databuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(databuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(databuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new databuku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu biaya;
    private javax.swing.JMenuItem biaya_buku;
    private javax.swing.JMenuItem biaya_gedung;
    private javax.swing.JMenuItem biaya_seragam;
    private javax.swing.JMenuItem biaya_spp;
    private javax.swing.JButton btnbersihkan;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JMenu data_admin;
    private javax.swing.JMenu data_guru;
    private javax.swing.JMenu data_siswa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel judul_buku;
    private javax.swing.JLabel kode_buku;
    private javax.swing.JMenu laporan;
    private javax.swing.JLabel mata_pelajaran;
    private javax.swing.JRadioButton rblks;
    private javax.swing.JRadioButton rbpaket;
    private javax.swing.JRadioButton rbsmt1;
    private javax.swing.JRadioButton rbsmt2;
    private javax.swing.JLabel semester;
    private javax.swing.JTable tabledatabuku;
    private javax.swing.JLabel tipe_buku;
    private javax.swing.JMenu transaksi;
    private javax.swing.JTextField txtjudulbuku;
    private javax.swing.JTextField txtkodebuku;
    private javax.swing.JTextField txtmapel;
    // End of variables declaration//GEN-END:variables
}
