/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.Random;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
/**
 *
 * @author adi
 */
public class formbuku extends javax.swing.JFrame {
    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;

    /**
     * Creates new form formbuku
     */
    public formbuku() {
        initComponents();
        datatable();
        rng_kode();
    }
    
    protected void aktif() {
        txtkodepembayaranbuku.setEnabled(true);
        txtkodebuku.setEnabled(true);
        txtnis.setEnabled(true);
        txtidguru.setEnabled(true);
        txtnamaguru.setEnabled(true);
        txtjudulbuku.setEnabled(true);
        cbxmatapelajaran.setEnabled(true);
        txthargabuku.setEnabled(true);
        cbxadmin.setEnabled(true);
    }
    
    protected void kosong() {
        txtkodepembayaranbuku.setText("");
        txtkodebuku.setText("");
        txtnis.setText("");
        txtidguru.setText("");
        txtnamaguru.setText("");
        txtjudulbuku.setText("");
        cbxmatapelajaran.setSelectedIndex(0);
        txthargabuku.setText("");
        cbxadmin.setSelectedIndex(0);
    }

    protected void datatable() {
        Object[] Baris = {"Kode Pembayaran Buku", "Kode Buku", "NIS", "ID Guru", "Nama Guru", "Judul Buku", "Mata Pelajaran", "Harga Buku", "Admin"};
        tabmode = new DefaultTableModel (null, Baris);
        databuku.setModel (tabmode);
        String sql ="SELECT * FROM pembayaranbuku";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery (sql);
            while (hasil.next()) {
                String a = hasil.getString("kd_pembayaranbuku");
                String b= hasil.getString("kode_buku");
                String c = hasil.getString("nis");
                String d = hasil.getString("id_guru");
                String e = hasil.getString("nama_guru");
                String f = hasil.getString("judul_buku");
                String g = hasil.getString("mata_pelajaran");
                String h = hasil.getString("harga_buku");
                String i = hasil.getString("admin");
                
                String[] data = {a,b,c,d,e,f,g,h,i};
                tabmode.addRow(data);
            }
        } catch (Exception e) {
        }
    }
    public void rng_kode() {
        int awal, akhir, hasil;
        Random rng = new Random();
        awal = 10000;
        akhir = 100000;
        hasil = rng.nextInt(akhir-awal)+awal;
        
        txtkodepembayaranbuku.setText(String.valueOf("PBK"+hasil));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtkodepembayaranbuku = new javax.swing.JTextField();
        txtnis = new javax.swing.JTextField();
        txtidguru = new javax.swing.JTextField();
        txtnamaguru = new javax.swing.JTextField();
        txtjudulbuku = new javax.swing.JTextField();
        btnsimpan = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        cbxmatapelajaran = new javax.swing.JComboBox();
        txthargabuku = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtkodebuku = new javax.swing.JTextField();
        btnedit = new javax.swing.JButton();
        btnbersihkan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        databuku = new javax.swing.JTable();
        cbxadmin = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel1.setText("Form Buku");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setText("Kode Pembayaran Buku ");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setText("NIS");

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setText("ID Guru");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel5.setText("Nama Guru");

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setText("Judul Buku");

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel7.setText("Harga Buku");

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel8.setText("Mata Pelajaran");

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel9.setText("Admin");

        txtkodepembayaranbuku.setEditable(false);
        txtkodepembayaranbuku.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N

        txtnis.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        txtnis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnisKeyTyped(evt);
            }
        });

        txtidguru.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        txtidguru.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtidguruKeyTyped(evt);
            }
        });

        txtnamaguru.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N

        txtjudulbuku.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N

        btnsimpan.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnhapus.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        cbxmatapelajaran.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        cbxmatapelajaran.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrasi Perkantoran", "Teknik Komputer Jaringan", "Akuntasi" }));
        cbxmatapelajaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxmatapelajaranActionPerformed(evt);
            }
        });

        txthargabuku.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        txthargabuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthargabukuActionPerformed(evt);
            }
        });
        txthargabuku.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txthargabukuKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel10.setText("Kode Buku");

        txtkodebuku.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N

        btnedit.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnedit.setText("Edit");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnbersihkan.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnbersihkan.setText("Bersihkan");
        btnbersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbersihkanActionPerformed(evt);
            }
        });

        databuku.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        databuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9"
            }
        ));
        databuku.setRowHeight(25);
        databuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                databukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(databuku);

        cbxadmin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Waskito Adhy P", "Andri Pratama", "Salza Silviastanti", "Sifa Maskury", "Sonia Agustina D.M", "Dwiki Charisma I", "Fajar Hidayatullah", "Zen Fanny P.P" }));

        jMenu1.setText("Data Siswa");
        jMenu1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jMenu1.setMargin(new java.awt.Insets(0, 5, 0, 5));
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Data Buku");
        jMenu2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jMenu2.setMargin(new java.awt.Insets(0, 5, 0, 5));
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Data Guru");
        jMenu3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jMenu3.setMargin(new java.awt.Insets(0, 5, 0, 5));
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Biaya");
        jMenu4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jMenu4.setMargin(new java.awt.Insets(0, 5, 0, 5));

        jMenuItem2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jMenuItem2.setText("Biaya SPP");
        jMenuItem2.setMargin(new java.awt.Insets(4, 0, 4, 0));
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jMenuItem3.setText("Biaya Buku");
        jMenuItem3.setMargin(new java.awt.Insets(4, 0, 4, 0));
        jMenu4.add(jMenuItem3);

        jMenuItem4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jMenuItem4.setText("Biaya Seragam");
        jMenuItem4.setMargin(new java.awt.Insets(4, 0, 4, 0));
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuItem5.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jMenuItem5.setText("Biaya Gedung");
        jMenuItem5.setMargin(new java.awt.Insets(4, 0, 4, 0));
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Transaksi ");
        jMenu5.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jMenu5.setMargin(new java.awt.Insets(0, 5, 0, 5));
        jMenuBar1.add(jMenu5);

        jMenu6.setText("Laporan");
        jMenu6.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jMenu6.setMargin(new java.awt.Insets(0, 5, 0, 5));
        jMenuBar1.add(jMenu6);

        jMenu7.setText("Data Admin TU");
        jMenu7.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jMenu7.setMargin(new java.awt.Insets(0, 5, 0, 5));
        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(139, 139, 139)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnbersihkan, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cbxadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnamaguru, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cbxmatapelajaran, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtjudulbuku, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtidguru, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(txtnis, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtkodepembayaranbuku, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtkodebuku, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(txthargabuku, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtkodepembayaranbuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtkodebuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtnis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtidguru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtnamaguru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtjudulbuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cbxmatapelajaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txthargabuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(cbxadmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbersihkan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxmatapelajaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxmatapelajaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxmatapelajaranActionPerformed

    private void txthargabukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthargabukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthargabukuActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
         String sql = "INSERT INTO pembayaranbuku VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, txtkodepembayaranbuku.getText());
            stat.setString(2, txtkodebuku.getText());
            stat.setString(3, txtnis.getText());
            stat.setString(4, txtidguru.getText());
            stat.setString(5, txtnamaguru.getText());
            stat.setString(6, txtjudulbuku.getText());
            stat.setString(7, cbxmatapelajaran.getSelectedItem().toString());
            stat.setString(8, txthargabuku.getText());
            stat.setString(9, cbxadmin.getSelectedItem().toString());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null,"Data Pembayaran Buku berhasil Disimpan");
            kosong();
            datatable();
            rng_kode();
            txtkodepembayaranbuku.requestFocus();
            
        } catch(SQLException e) {
            JOptionPane.showMessageDialog(null,"Data Pembayaran Buku Gagal Disimpan" +e);
        }                        
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null,"hapus","Konfirmasi Dialog", JOptionPane.YES_NO_CANCEL_OPTION);
        if (ok == 0) {
            String sql ="DELETE FROM pembayaranbuku WHERE kd_pembayaranbuku = '"+txtkodepembayaranbuku.getText()+"'";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Pembayaran Buku Berhasil Diubah");
                kosong ();
                txtkodepembayaranbuku.requestFocus();
                datatable();
                rng_kode();
            }catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "Data Pembayaran Buku Gagal Diubah"+e);
            }                                       
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        try {
            String sql ="UPDATE pembayaranbuku SET kode_buku=?, nis=?, id_guru=?, nama_guru=?, judul_buku=?, mata_pelajaran=?, harga_buku=?, admin=? WHERE kd_pembayaranbuku=?";
            PreparedStatement stat = conn.prepareStatement(sql);
            
            stat.setString(1, txtkodebuku.getText());
            stat.setString(2, txtnis.getText());
            stat.setString(3, txtidguru.getText());
            stat.setString(4, txtnamaguru.getText());
            stat.setString(5, txtjudulbuku.getText());
            stat.setString(6, cbxmatapelajaran.getSelectedItem().toString());
            stat.setString(7, txthargabuku.getText());
            stat.setString(8, cbxadmin.getSelectedItem().toString());
            stat.setString(9, txtkodepembayaranbuku.getText());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null,"Data Pembayaran Buku Berhasil diubah");
            kosong();
            datatable();
            rng_kode();
            txtkodepembayaranbuku.requestFocus();
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Data Pembayaran Buku Gagal diubah"+e);
        }                                                           
    }//GEN-LAST:event_btneditActionPerformed

    private void btnbersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbersihkanActionPerformed
        // TODO add your handling code here:
        kosong();
        rng_kode();
    }//GEN-LAST:event_btnbersihkanActionPerformed

    private void databukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_databukuMouseClicked
        // TODO add your handling code here:
         int bar = databuku.getSelectedRow();
        String a = tabmode.getValueAt(bar, 0).toString();
        String b = tabmode.getValueAt(bar, 1).toString();
        String c = tabmode.getValueAt(bar, 2).toString();
        String d = tabmode.getValueAt(bar, 3).toString();
        String e = tabmode.getValueAt(bar, 4).toString();
        String f = tabmode.getValueAt(bar, 5).toString();
        String g = tabmode.getValueAt(bar, 6).toString();
        String h = tabmode.getValueAt(bar, 7).toString();
        String i = tabmode.getValueAt(bar, 8).toString();
        
        txtkodepembayaranbuku.setText(a);
        txtkodebuku.setText(b);
        
        txtnis.setText(c);
        txtidguru.setText(d);
        txtnamaguru.setText(e);
        
        txtjudulbuku.setText(f);
        cbxmatapelajaran.setSelectedItem(g);
        txthargabuku.setText(h);
        cbxadmin.setSelectedItem(i);
    }//GEN-LAST:event_databukuMouseClicked

    private void txthargabukuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthargabukuKeyTyped
        // TODO add your handling code here:
        char biaya = evt.getKeyChar();
            if(!Character.isDigit(biaya)||(biaya == KeyEvent.VK_BACK_SPACE|| biaya == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_txthargabukuKeyTyped

    private void txtnisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnisKeyTyped
        // TODO add your handling code here:
        char nis = evt.getKeyChar();
            if(!Character.isDigit(nis)||(nis == KeyEvent.VK_BACK_SPACE|| nis == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtnisKeyTyped

    private void txtidguruKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidguruKeyTyped
        // TODO add your handling code here:
        char id = evt.getKeyChar();
            if(!Character.isDigit(id)||(id == KeyEvent.VK_BACK_SPACE|| id == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtidguruKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formbuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formbuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formbuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formbuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formbuku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbersihkan;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JComboBox<String> cbxadmin;
    private javax.swing.JComboBox cbxmatapelajaran;
    private javax.swing.JTable databuku;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txthargabuku;
    private javax.swing.JTextField txtidguru;
    private javax.swing.JTextField txtjudulbuku;
    private javax.swing.JTextField txtkodebuku;
    private javax.swing.JTextField txtkodepembayaranbuku;
    private javax.swing.JTextField txtnamaguru;
    private javax.swing.JTextField txtnis;
    // End of variables declaration//GEN-END:variables
}
