/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.JFrame;
import com.toedter.calendar.JDateChooser;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author deb
 */
public class formpendataansiswa extends javax.swing.JFrame {
    private Connection conn = new koneksi().connect();
    private JDateChooser chooser;
    private DefaultTableModel tabmode;
    /**
     * Creates new form formpendaftaransiswa
     */
    public formpendataansiswa() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        tablesiswa();
    }
    
    protected void aktif() {
        txtnis.setEnabled(true);
        txtnamalengkap.setEnabled(true);
        txtnotelepon.setEnabled(true);
        txttempat.setEnabled(true);
        datetgllahir.setEnabled(true);
        txtareaalamat.setEnabled(true);
        rblaki.setSelected(true);
    }
    protected void kosong() {
        txtnis.setText("");
        txtnis.setEditable(true);
        txtnamalengkap.setText("");
        txtnotelepon.setText("");
        txttempat.setText("");
        datetgllahir.setDate(null);
        rblaki.setSelected(true);
        rbperempuan.setSelected(false);
        cbxagama.setSelectedIndex(0);
        cbxjurusan.setSelectedIndex(0);
        txtareaalamat.setText("");
    }
    protected void tablesiswa() {
        Object[] Data = {"NIS", "Nama Siswa", "No Telepon", "Tempat Lahir", "Tanggal Lahir", "Jenis Kelamin", "Agama", "Jurusan", "Alamat"};
        tabmode = new DefaultTableModel(null, Data);
        datatablesiswa.setModel(tabmode);
        String sql = "SELECT * FROM datasiswa";
        try {
            
            java.sql.Statement stat = conn.createStatement();
            ResultSet datasiswa = stat.executeQuery(sql);
            while(datasiswa.next()) {
                String nissiswa = datasiswa.getString("nis");
                String namasiswa = datasiswa.getString("nama");
                String notelpsiswa = datasiswa.getString("notelp");
                String tmptlahirsiswa = datasiswa.getString("tempatlahir");
                String tgllahirsiswa = datasiswa.getString("tgllahir");
                String jksiswa = datasiswa.getString("jk");
                String agamasiswa = datasiswa.getString("agama");
                String jurusansiswa = datasiswa.getString("jurusan");
                String alamatsiswa = datasiswa.getString("alamat");

                String[] data = {nissiswa, namasiswa, notelpsiswa, tmptlahirsiswa, tgllahirsiswa, jksiswa, agamasiswa, jurusansiswa, alamatsiswa};
                tabmode.addRow(data);
            }
        } catch (Exception e) {
            
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jldatasiswa = new javax.swing.JLabel();
        jlnama = new javax.swing.JLabel();
        jlttl = new javax.swing.JLabel();
        jljk = new javax.swing.JLabel();
        jlagama = new javax.swing.JLabel();
        jljurusan = new javax.swing.JLabel();
        jlnotelepon = new javax.swing.JLabel();
        jlnis = new javax.swing.JLabel();
        jlalamat = new javax.swing.JLabel();
        txtnis = new javax.swing.JTextField();
        txtnamalengkap = new javax.swing.JTextField();
        txttempat = new javax.swing.JTextField();
        cbxagama = new javax.swing.JComboBox<>();
        txtnotelepon = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtareaalamat = new javax.swing.JTextArea();
        cbxjurusan = new javax.swing.JComboBox<>();
        btnsimpan = new javax.swing.JButton();
        btnbersihkan = new javax.swing.JButton();
        rblaki = new javax.swing.JRadioButton();
        rbperempuan = new javax.swing.JRadioButton();
        warnnis = new javax.swing.JLabel();
        warnnama = new javax.swing.JLabel();
        warnnotelp = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        datatablesiswa = new javax.swing.JTable();
        btnedit = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        databuku = new javax.swing.JMenu();
        dataguru = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        biayaspp = new javax.swing.JMenuItem();
        biayabuku = new javax.swing.JMenuItem();
        biayaseragam = new javax.swing.JMenuItem();
        biayagedung = new javax.swing.JMenuItem();
        transaksi = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        dataadmintu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1920, 1080));

        jldatasiswa.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jldatasiswa.setText("Data Siswa ");

        jlnama.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jlnama.setText("Nama Lengkap ");

        jlttl.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jlttl.setText("Tempat Lahir");

        jljk.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jljk.setText("Jenis Kelamin");

        jlagama.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jlagama.setText("Agama");

        jljurusan.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jljurusan.setText("Jurusan");

        jlnotelepon.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jlnotelepon.setText("No.Telepon");

        jlnis.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jlnis.setText("NIS");

        jlalamat.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jlalamat.setText("Alamat Tempat Tinggal");

        txtnis.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        txtnis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnisKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnisKeyTyped(evt);
            }
        });

        txtnamalengkap.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        txtnamalengkap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnamalengkapKeyReleased(evt);
            }
        });

        txttempat.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        txttempat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttempatActionPerformed(evt);
            }
        });
        txttempat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txttempatKeyReleased(evt);
            }
        });

        cbxagama.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        cbxagama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Islam", "Katolik", "Kristen Protestan", "Hindu", "Buddha", "Khonghucu" }));

        txtnotelepon.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        txtnotelepon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnoteleponKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnoteleponKeyTyped(evt);
            }
        });

        txtareaalamat.setColumns(20);
        txtareaalamat.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        txtareaalamat.setRows(5);
        txtareaalamat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtareaalamatKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(txtareaalamat);

        cbxjurusan.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        cbxjurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrasi Perkantoran", "Akutansi", "Teknik Komputer dan Jaringan" }));

        btnsimpan.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnbersihkan.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnbersihkan.setText("Bersihkan");
        btnbersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbersihkanActionPerformed(evt);
            }
        });

        rblaki.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        rblaki.setSelected(true);
        rblaki.setText("Laki-laki");
        rblaki.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rblakiMouseClicked(evt);
            }
        });

        rbperempuan.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        rbperempuan.setText("Perempuan");
        rbperempuan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbperempuanMouseClicked(evt);
            }
        });

        warnnis.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        warnnis.setForeground(new java.awt.Color(255, 51, 51));

        warnnama.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        warnnama.setForeground(new java.awt.Color(255, 51, 51));
        warnnama.setToolTipText("");

        warnnotelp.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        warnnotelp.setForeground(new java.awt.Color(255, 51, 51));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setText("Tanggal Lahir");

        datatablesiswa.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        datatablesiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9"
            }
        ));
        datatablesiswa.setRowHeight(25);
        datatablesiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                datatablesiswaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(datatablesiswa);

        btnedit.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnedit.setText("Edit");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnhapus.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        jMenuBar1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        jMenu1.setText("Data Siswa");
        jMenu1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jMenu1.setMargin(new java.awt.Insets(0, 5, 0, 5));
        jMenuBar1.add(jMenu1);

        databuku.setText("Data Buku");
        databuku.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        databuku.setMargin(new java.awt.Insets(0, 5, 0, 5));
        databuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                databukuMouseClicked(evt);
            }
        });
        databuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                databukuActionPerformed(evt);
            }
        });
        jMenuBar1.add(databuku);

        dataguru.setText("Data Guru");
        dataguru.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        dataguru.setMargin(new java.awt.Insets(0, 5, 0, 5));
        dataguru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataguruMouseClicked(evt);
            }
        });
        jMenuBar1.add(dataguru);

        jMenu4.setText("Biaya");
        jMenu4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jMenu4.setMargin(new java.awt.Insets(0, 5, 0, 5));

        biayaspp.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        biayaspp.setText("Biaya SPP");
        biayaspp.setMargin(new java.awt.Insets(4, 0, 4, 0));
        biayaspp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                biayasppMouseClicked(evt);
            }
        });
        biayaspp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biayasppActionPerformed(evt);
            }
        });
        jMenu4.add(biayaspp);

        biayabuku.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        biayabuku.setText("Biaya Buku");
        biayabuku.setMargin(new java.awt.Insets(4, 0, 4, 0));
        biayabuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                biayabukuMouseClicked(evt);
            }
        });
        jMenu4.add(biayabuku);

        biayaseragam.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        biayaseragam.setText("Biaya Seragam");
        biayaseragam.setMargin(new java.awt.Insets(4, 0, 4, 0));
        biayaseragam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                biayaseragamMouseClicked(evt);
            }
        });
        jMenu4.add(biayaseragam);

        biayagedung.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        biayagedung.setText("Biaya Gedung");
        biayagedung.setMargin(new java.awt.Insets(4, 0, 4, 0));
        biayagedung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                biayagedungMouseClicked(evt);
            }
        });
        jMenu4.add(biayagedung);

        jMenuBar1.add(jMenu4);

        transaksi.setText("Transaksi");
        transaksi.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        transaksi.setMargin(new java.awt.Insets(0, 5, 0, 5));
        jMenuBar1.add(transaksi);

        jMenu6.setText("Laporan");
        jMenu6.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jMenu6.setMargin(new java.awt.Insets(0, 5, 0, 5));
        jMenuBar1.add(jMenu6);

        dataadmintu.setText("Data Admin TU");
        dataadmintu.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        dataadmintu.setMargin(new java.awt.Insets(0, 5, 0, 5));
        dataadmintu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataadmintuMouseClicked(evt);
            }
        });
        jMenuBar1.add(dataadmintu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jljk)
                                    .addComponent(jlagama)
                                    .addComponent(jljurusan)
                                    .addComponent(jlalamat))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(25, 25, 25)
                                        .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(25, 25, 25)
                                        .addComponent(btnbersihkan, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(25, 25, 25)
                                        .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rblaki)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbperempuan))
                                    .addComponent(cbxagama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxjurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlnotelepon)
                                    .addComponent(jlnama)
                                    .addComponent(jlttl)
                                    .addComponent(jlnis)
                                    .addComponent(jldatasiswa)
                                    .addComponent(jLabel1))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txttempat, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtnis, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtnamalengkap, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtnotelepon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(warnnis)
                                            .addComponent(warnnama)
                                            .addComponent(warnnotelp)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(334, 334, 334))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(720, 720, 720)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jldatasiswa)
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlnis)
                            .addComponent(txtnis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(warnnis))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlnama)
                            .addComponent(txtnamalengkap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(warnnama))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlnotelepon)
                            .addComponent(txtnotelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(warnnotelp))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlttl)
                            .addComponent(txttempat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1)
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jljk)
                            .addComponent(rblaki)
                            .addComponent(rbperempuan))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlagama)
                            .addComponent(cbxagama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jljurusan)
                            .addComponent(cbxjurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlalamat)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnbersihkan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txttempatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttempatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttempatActionPerformed

    private void txtnisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnisKeyTyped
        // TODO add your handling code here:
        char nis = evt.getKeyChar();
            if(!Character.isDigit(nis)||(nis == KeyEvent.VK_BACK_SPACE|| nis == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtnisKeyTyped

    private void txtnoteleponKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnoteleponKeyTyped
        // TODO add your handling code here:
        char notelp= evt.getKeyChar();
            if(!Character.isDigit(notelp)||(notelp == KeyEvent.VK_BACK_SPACE|| notelp == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtnoteleponKeyTyped

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        String sql = "INSERT INTO datasiswa VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
        
        if(txtnis.getText().trim().isEmpty() && txtnamalengkap.getText().trim().isEmpty() &&
            txtnotelepon.getText().trim().isEmpty()) {
            
            warnnis.setText("NIS Wajib Diisi!");
            warnnama.setText("Nama Wajib Diisi!");
            warnnotelp.setText("No Telepon Wajib Diisi!");
            
        } else if(txtnis.getText().trim().isEmpty()){
            warnnis.setText("NIS Wajib Diisi!");
        } else if(txtnamalengkap.getText().trim().isEmpty()){
            warnnama.setText("Nama Wajib Diisi!");
        } else if(txtnotelepon.getText().trim().isEmpty()){
            warnnotelp.setText("No Telepon Wajib Diisi!");
        } else
        
        try {
            PreparedStatement datasiswa = conn.prepareStatement(sql);
            datasiswa.setString(1, txtnis.getText());
            datasiswa.setString(2, txtnamalengkap.getText());
            datasiswa.setString(3, txtnotelepon.getText());
            datasiswa.setString(4, txttempat.getText());
            
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date = sdf.format(datetgllahir.getDate());
            datasiswa.setString(5, date);
            
            String jkel = "";
            if(rblaki.isSelected()) jkel = "Laki - laki";
            else jkel = "Perempuan";
            datasiswa.setString(6, jkel);
            
            datasiswa.setString(7, cbxagama.getSelectedItem().toString());
            datasiswa.setString(8, cbxjurusan.getSelectedItem().toString());
            datasiswa.setString(9, txtareaalamat.getText());
            
            datasiswa.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Siswa Berhasil Disimpan");
            kosong();
            txtnis.requestFocus();
            tablesiswa();
            
            } catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Data Siswa Gagal Disimpan");
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void rblakiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rblakiMouseClicked
        // TODO add your handling code here:
        if(rblaki.isSelected())
            rbperempuan.setSelected(false);
    }//GEN-LAST:event_rblakiMouseClicked

    private void rbperempuanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbperempuanMouseClicked
        // TODO add your handling code here:
        if(rbperempuan.isSelected())
            rblaki.setSelected(false);
    }//GEN-LAST:event_rbperempuanMouseClicked

    private void txtnisKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnisKeyReleased
        // TODO add your handling code here:
        warnnis.setText("");
    }//GEN-LAST:event_txtnisKeyReleased

    private void txtnamalengkapKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnamalengkapKeyReleased
        // TODO add your handling code here:
        warnnama.setText("");
    }//GEN-LAST:event_txtnamalengkapKeyReleased

    private void txtnoteleponKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnoteleponKeyReleased
        // TODO add your handling code here:
        warnnotelp.setText("");
    }//GEN-LAST:event_txtnoteleponKeyReleased

    private void txttempatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttempatKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txttempatKeyReleased

    private void txtareaalamatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtareaalamatKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtareaalamatKeyReleased

    private void btnbersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbersihkanActionPerformed
        // TODO add your handling code here:
        kosong();
    }//GEN-LAST:event_btnbersihkanActionPerformed

    private void datatablesiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datatablesiswaMouseClicked
        // TODO add your handling code here:
        
        try {
            tabmode = (DefaultTableModel)datatablesiswa.getModel();
            
            int bar = datatablesiswa.getSelectedRow();
            String nis = tabmode.getValueAt(bar, 0).toString();
            String nama = tabmode.getValueAt(bar, 1).toString();
            String notelp = tabmode.getValueAt(bar, 2).toString();
            String tmptlahir = tabmode.getValueAt(bar, 3).toString();
            
            java.util.Date tgllahir = new SimpleDateFormat("yyyy-MM-dd").parse((String)tabmode.getValueAt(bar, 4));
            
            String jk = tabmode.getValueAt(bar, 5).toString();
            String agama = tabmode.getValueAt(bar, 6).toString();
            String jurusan = tabmode.getValueAt(bar, 7).toString();
            String alamat = tabmode.getValueAt(bar, 8).toString();

            txtnis.setText(nis);
            txtnis.setEditable(false);
            
            txtnamalengkap.setText(nama);
            txtnotelepon.setText(notelp);
            txttempat.setText(tmptlahir);
            datetgllahir.setDate(tgllahir);
        
            if(jk.equals("Laki - laki")) {
                rblaki.setSelected(true); 
                rbperempuan.setSelected(false);
            } else {
                rblaki.setSelected(false); 
                rbperempuan.setSelected(true);
            }

            cbxagama.setSelectedItem(agama);
            cbxjurusan.setSelectedItem(jurusan);
            txtareaalamat.setText(alamat);
        } catch (ParseException ex) {
            Logger.getLogger(formpendataansiswa.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_datatablesiswaMouseClicked

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "UPDATE datasiswa SET nama=?, notelp=?, tempatlahir=?, tgllahir=?, jk=?, agama=?, jurusan=?, alamat=? WHERE nis=?";
            PreparedStatement stat = conn.prepareStatement(sql);
            
            stat.setString(1, txtnamalengkap.getText());
            stat.setString(2, txtnotelepon.getText());
            stat.setString(3, txttempat.getText());
            
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date = sdf.format(datetgllahir.getDate());
            stat.setString(4, date);
            
            String jkel="";
            if(rblaki.isSelected()) jkel="Laki - laki";
            else jkel = "Perempuan";
            stat.setString(5, jkel);
            
            stat.setString(6, cbxagama.getSelectedItem().toString());
            stat.setString(7, cbxjurusan.getSelectedItem().toString());
            stat.setString(8, txtareaalamat.getText());
            stat.setString(9, txtnis.getText());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Siswa Berhasil Diubah");
            kosong();
            txtnis.requestFocus();
            tablesiswa();
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Siswa Gagal Diubah"+e);
        }
    }//GEN-LAST:event_btneditActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null, "Hapus Data Siswa ?", "Menghapus Data", JOptionPane.YES_NO_CANCEL_OPTION);
        if (ok == 0 ) {
            String sql = "DELETE FROM datasiswa WHERE nis='"+txtnis.getText()+"'";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Siswa Dihapus");
                kosong();
                txtnis.requestFocus();
                tablesiswa();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Data Siswa Gagal Dihapus"+e);
            }
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void databukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_databukuActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_databukuActionPerformed

    private void biayasppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biayasppActionPerformed
        // TODO add your handling code here:
        formpembayaranspp buku = new formpembayaranspp();
        buku.setVisible(true);
        this.setVisible(false);
        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        this.dispose(); 
    }//GEN-LAST:event_biayasppActionPerformed

    private void databukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_databukuMouseClicked
        // TODO add your handling code here:
        databuku buku = new databuku();
        buku.setVisible(true);
        this.setVisible(false);
        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_databukuMouseClicked

    private void dataguruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataguruMouseClicked
        // TODO add your handling code here:
        formdataguru guru = new formdataguru();
        guru.setVisible(true);
        this.setVisible(false);
        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_dataguruMouseClicked

    private void biayasppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_biayasppMouseClicked
        // TODO add your handling code here:
        formpembayaranspp spp = new formpembayaranspp();
        spp.setVisible(true);
        this.setVisible(false);
        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_biayasppMouseClicked

    private void biayabukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_biayabukuMouseClicked
        // TODO add your handling code here:
        formbuku buku = new formbuku();
        buku.setVisible(true);
        this.setVisible(false);
        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_biayabukuMouseClicked

    private void biayaseragamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_biayaseragamMouseClicked
        // TODO add your handling code here:
        seragam seragam = new seragam();
        seragam.setVisible(true);
        this.setVisible(false);
        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_biayaseragamMouseClicked

    private void biayagedungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_biayagedungMouseClicked
        // TODO add your handling code here:
        formgedung gedung = new formgedung();
        gedung.setVisible(true);
        this.setVisible(false);
        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_biayagedungMouseClicked

    private void dataadmintuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataadmintuMouseClicked
        // TODO add your handling code here:
        formadmintu admin = new formadmintu();
        admin.setVisible(true);
        this.setVisible(false);
        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_dataadmintuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formpendataansiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formpendataansiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formpendataansiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formpendataansiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formpendataansiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem biayabuku;
    private javax.swing.JMenuItem biayagedung;
    private javax.swing.JMenuItem biayaseragam;
    private javax.swing.JMenuItem biayaspp;
    private javax.swing.JButton btnbersihkan;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnsimpan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbxagama;
    private javax.swing.JComboBox<String> cbxjurusan;
    private javax.swing.JMenu dataadmintu;
    private javax.swing.JMenu databuku;
    private javax.swing.JMenu dataguru;
    private javax.swing.JTable datatablesiswa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlagama;
    private javax.swing.JLabel jlalamat;
    private javax.swing.JLabel jldatasiswa;
    private javax.swing.JLabel jljk;
    private javax.swing.JLabel jljurusan;
    private javax.swing.JLabel jlnama;
    private javax.swing.JLabel jlnis;
    private javax.swing.JLabel jlnotelepon;
    private javax.swing.JLabel jlttl;
    private javax.swing.JRadioButton rblaki;
    private javax.swing.JRadioButton rbperempuan;
    private javax.swing.JMenu transaksi;
    private javax.swing.JTextArea txtareaalamat;
    private javax.swing.JTextField txtnamalengkap;
    private javax.swing.JTextField txtnis;
    private javax.swing.JTextField txtnotelepon;
    private javax.swing.JTextField txttempat;
    private javax.swing.JLabel warnnama;
    private javax.swing.JLabel warnnis;
    private javax.swing.JLabel warnnotelp;
    // End of variables declaration//GEN-END:variables
}
