/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;

import com.toedter.calendar.JDateChooser;
import java.sql.*;
import java.text.ParseException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Sifa M
 */
public class formadmintu extends javax.swing.JFrame {
    private JDateChooser chooser;
    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;

    /**
     * Creates new form formadminTU
     */
    public formadmintu() {
        initComponents();
        datatable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jeniskelamin = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtidadmin = new javax.swing.JTextField();
        txttempat = new javax.swing.JTextField();
        txtnotelpon = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        btnsimpan = new javax.swing.JButton();
        bbersihkan = new javax.swing.JButton();
        btnkeluar = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        rblakilaki = new javax.swing.JRadioButton();
        rbperempuan = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtareaalamat = new javax.swing.JTextArea();
        txtnama = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabeladmintu = new javax.swing.JTable();
        btnhapus = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tgllahir = new com.toedter.calendar.JDateChooser();
        jMenuBar1 = new javax.swing.JMenuBar();
        data_siswa = new javax.swing.JMenu();
        data_buku = new javax.swing.JMenu();
        data_guru = new javax.swing.JMenu();
        biaya = new javax.swing.JMenu();
        biaya_spp = new javax.swing.JMenuItem();
        biaya_buku = new javax.swing.JMenuItem();
        biaya_seragam = new javax.swing.JMenuItem();
        biaya_gedung = new javax.swing.JMenuItem();
        transaksi = new javax.swing.JMenu();
        laporan = new javax.swing.JMenu();
        data_admintu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        jLabel1.setText("Form Admin TU");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setText("Nama");

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setText("Tempat Lahir");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel5.setText("E-Mail");

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setText("ID Admin");

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel7.setText("Nomor Telpon");

        txtidadmin.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N

        txttempat.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N

        txtnotelpon.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N

        txtemail.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N

        btnsimpan.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        btnsimpan.setText("SIMPAN");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        bbersihkan.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        bbersihkan.setText("BERSIHKAN");
        bbersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbersihkanActionPerformed(evt);
            }
        });

        btnkeluar.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        btnkeluar.setText("KELUAR");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });

        btnedit.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        btnedit.setText("EDIT");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel8.setText("Jenis Kelamin");

        jeniskelamin.add(rblakilaki);
        rblakilaki.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        rblakilaki.setText("Laki - Laki");

        jeniskelamin.add(rbperempuan);
        rbperempuan.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        rbperempuan.setText("Perempuan");

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel9.setText("Alamat");

        txtareaalamat.setColumns(20);
        txtareaalamat.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        txtareaalamat.setRows(5);
        jScrollPane1.setViewportView(txtareaalamat);

        txtnama.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N

        tabeladmintu.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        tabeladmintu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        tabeladmintu.setRowHeight(25);
        tabeladmintu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabeladmintuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabeladmintu);

        btnhapus.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        btnhapus.setText("HAPUS");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setText("Tanggal Lahir");

        tgllahir.setDateFormatString("yyyy-MM-dd");
        tgllahir.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N

        data_siswa.setText("Data Siswa");
        data_siswa.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        data_siswa.setMargin(new java.awt.Insets(0, 5, 0, 5));
        jMenuBar1.add(data_siswa);

        data_buku.setText("Data Buku");
        data_buku.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        data_buku.setMargin(new java.awt.Insets(0, 5, 0, 5));
        jMenuBar1.add(data_buku);

        data_guru.setText("Data Guru");
        data_guru.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        data_guru.setMargin(new java.awt.Insets(0, 5, 0, 5));
        jMenuBar1.add(data_guru);

        biaya.setText("Biaya");
        biaya.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        biaya.setMargin(new java.awt.Insets(0, 5, 0, 5));

        biaya_spp.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        biaya_spp.setText("Biaya SPP");
        biaya_spp.setMargin(new java.awt.Insets(4, 0, 4, 0));
        biaya_spp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biaya_sppActionPerformed(evt);
            }
        });
        biaya.add(biaya_spp);

        biaya_buku.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        biaya_buku.setText("Biaya Buku");
        biaya_buku.setMargin(new java.awt.Insets(4, 0, 4, 0));
        biaya.add(biaya_buku);

        biaya_seragam.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        biaya_seragam.setText("Biaya Seragam");
        biaya_seragam.setMargin(new java.awt.Insets(4, 0, 4, 0));
        biaya.add(biaya_seragam);

        biaya_gedung.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        biaya_gedung.setText("Biaya Gedung");
        biaya_gedung.setMargin(new java.awt.Insets(4, 0, 4, 0));
        biaya.add(biaya_gedung);

        jMenuBar1.add(biaya);

        transaksi.setText("Transaksi");
        transaksi.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        transaksi.setMargin(new java.awt.Insets(0, 5, 0, 5));
        jMenuBar1.add(transaksi);

        laporan.setText("Laporan");
        laporan.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        laporan.setMargin(new java.awt.Insets(0, 5, 0, 5));
        jMenuBar1.add(laporan);

        data_admintu.setText("Data Admin TU");
        data_admintu.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        data_admintu.setMargin(new java.awt.Insets(0, 5, 0, 5));
        data_admintu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_admintuActionPerformed(evt);
            }
        });
        jMenuBar1.add(data_admintu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(538, 538, 538)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel2))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(rblakilaki)
                                            .addGap(18, 18, 18)
                                            .addComponent(rbperempuan)
                                            .addGap(57, 57, 57))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                            .addComponent(txtemail, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtnotelpon, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtnama, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtidadmin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txttempat, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tgllahir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 285, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1049, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bbersihkan, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtidadmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttempat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(tgllahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rblakilaki)
                                    .addComponent(rbperempuan)
                                    .addComponent(jLabel8))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtnotelpon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(25, 25, 25)
                                .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bbersihkan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(312, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    protected void aktif(){
        txtidadmin.setEnabled(true);
        txtnama.setEnabled(true);
        txttempat.setEnabled(true);
        txtnotelpon.setEnabled(true);
        txtemail.setEnabled(true);
        txtareaalamat.setEnabled(true);
    }
    
    protected void bersihkan(){
        txtidadmin.setText("");
        txtnama.setText("");
        txttempat.setText("");
        tgllahir.setDate(null);
        jeniskelamin.clearSelection();
        txtnotelpon.setText("");
        txtemail.setText("");
        txtareaalamat.setText("");
    }
    private void bbersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbersihkanActionPerformed
        // TODO add your handling code here:
        bersihkan();
    }//GEN-LAST:event_bbersihkanActionPerformed

    protected void datatable(){
        Object[] Baris = {"ID Admin", "Nama", "Tempat", "Tanggal Lahir", "Jenis Kelamin", "No Telepon", "E-mail", "Alamat"};
        tabmode = new DefaultTableModel(null, Baris);
        tabeladmintu.setModel(tabmode);
        String sql = "SELECT id_admin, nama, tempat, tgl_lahir, jenis_kelamin, no_telpon, email, alamat FROM admintu";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String a = hasil.getString("id_admin");
                String b = hasil.getString("nama");
                String c = hasil.getString("tempat");
                String d = hasil.getString("tgl_lahir");
                String e = hasil.getString("jenis_kelamin");
                String f = hasil.getString("no_telpon");
                String g = hasil.getString("email");
                String h = hasil.getString("alamat");
                
                String[] data = {a, b, c, d, e, f, g, h};
                tabmode.addRow(data);
                }
            } catch (Exception e){
            }
    }
    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        
        String sql = "insert into admintu values (?, ?, ?, ?, ?, ?, ?, ?)";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, txtidadmin.getText());
            stat.setString(2, txtnama.getText());
            stat.setString(3, txttempat.getText());
            
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date = sdf.format(tgllahir.getDate());
            stat.setString(4, date);
            
            String jenis_kelamin="";
            if(rblakilaki.isSelected()) jenis_kelamin="Laki-laki";
            else jenis_kelamin="Perempuan";
            
            stat.setString(5, jenis_kelamin);
            stat.setString(6, txtnotelpon.getText());
            stat.setString(7, txtemail.getText());
            stat.setString(8, txtareaalamat.getText());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Admin Berhasil Disimpan");
            bersihkan();
            txtidadmin.requestFocus();
            datatable();
            
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Admin Gagal Disimpan"+e);
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "UPDATE admintu SET nama=?, tempat=?, tgl_lahir=?, jenis_kelamin=?, no_telpon=?, email=?, alamat=? WHERE id_admin=?";
            PreparedStatement stat = conn.prepareStatement(sql);
            
            stat.setString(1, txtnama.getText());
            stat.setString(2, txttempat.getText());
            
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date = sdf.format(tgllahir.getDate());
            stat.setString(3, date);
            
            String jenis_kelamin="";
            if(rblakilaki.isSelected()) jenis_kelamin = "Laki-laki";
            else jenis_kelamin = "Perempuan";
            stat.setString(4, jenis_kelamin);
            
            stat.setString(5, txtnotelpon.getText());
            stat.setString(6, txtemail.getText());
            stat.setString(7, txtareaalamat.getText());
            stat.setString(8, txtidadmin.getText());
            
            stat.executeUpdate();
            txtidadmin.requestFocus();
            JOptionPane.showMessageDialog(null, "Data Admin Berhasil Diubah");
            bersihkan();
            datatable();
            
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Admin Gagal Diubah"+e);
        }
    }//GEN-LAST:event_btneditActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnkeluarActionPerformed

    private void biaya_sppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biaya_sppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_biaya_sppActionPerformed

    private void data_admintuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_admintuActionPerformed
        // TODO add your handling code here:
        new formadmintu().setVisible(true);
    }//GEN-LAST:event_data_admintuActionPerformed

    private void tabeladmintuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabeladmintuMouseClicked
        // TODO add your handling code here:
        try {
            int bar = tabeladmintu.getSelectedRow();
            String a = tabmode.getValueAt(bar, 0).toString();
            String b = tabmode.getValueAt(bar, 1).toString();
            String c = tabmode.getValueAt(bar, 2).toString();

            java.util.Date d = new SimpleDateFormat("yyyy-MM-dd").parse((String)tabmode.getValueAt(bar, 3));

            String e = tabmode.getValueAt(bar, 4).toString();
            String f = tabmode.getValueAt(bar, 5).toString();
            String g = tabmode.getValueAt(bar, 6).toString();
            String h = tabmode.getValueAt(bar, 7).toString();

            txtidadmin.setText(a);
            txtnama.setText(b);
            txttempat.setText(c);
            tgllahir.setDate(d);

            if(e.equals("Laki-laki")) {
                rblakilaki.setSelected(true); 
                rbperempuan.setSelected(false);
            } else {
                rblakilaki.setSelected(false); 
                rbperempuan.setSelected(true);
            }

            txtnotelpon.setText(f);
            txtemail.setText(g);
            txtareaalamat.setText(h);
        
        } catch (ParseException ex) {
            Logger.getLogger(formadmintu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_tabeladmintuMouseClicked

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null,"hapus","Konfirmasi Dialog", JOptionPane.YES_NO_CANCEL_OPTION);
        if (ok==0){
            String sql = "delete from admintu where id_admin ='"+txtidadmin.getText()+"'";
            try{
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Admin berhasil dihapus");
                bersihkan();
                txtidadmin.requestFocus();
                datatable();
            }catch (SQLException e){
                JOptionPane.showMessageDialog(null, "Data Admin gagal dihapus" +e);
            }
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formadmintu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formadmintu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formadmintu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formadmintu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formadmintu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbersihkan;
    private javax.swing.JMenu biaya;
    private javax.swing.JMenuItem biaya_buku;
    private javax.swing.JMenuItem biaya_gedung;
    private javax.swing.JMenuItem biaya_seragam;
    private javax.swing.JMenuItem biaya_spp;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JMenu data_admintu;
    private javax.swing.JMenu data_buku;
    private javax.swing.JMenu data_guru;
    private javax.swing.JMenu data_siswa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.ButtonGroup jeniskelamin;
    private javax.swing.JMenu laporan;
    private javax.swing.JRadioButton rblakilaki;
    private javax.swing.JRadioButton rbperempuan;
    private javax.swing.JTable tabeladmintu;
    private com.toedter.calendar.JDateChooser tgllahir;
    private javax.swing.JMenu transaksi;
    private javax.swing.JTextArea txtareaalamat;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtidadmin;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnotelpon;
    private javax.swing.JTextField txttempat;
    // End of variables declaration//GEN-END:variables
}
