/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;

import com.toedter.calendar.JDateChooser;
import java.sql.*;
import java.text.ParseException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author User
 */
public class formdataguru extends javax.swing.JFrame {
    private JDateChooser chooser;
    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;

    /**
     * Creates new form formdataguru
     */
    public formdataguru() {
        initComponents();
        datatable();
    }
    protected void aktif(){
        txtidguru.setEnabled(true);
        txtnama.setEnabled(true);
        txtmapel.setEnabled(true);
        txtnotelp.setEnabled(true);
        txtemail.setEnabled(true);
        txtareaalamat.setEnabled(true);
    }
    protected void kosong(){
        txtidguru.setText("");
        txtnama.setText("");
        txtmapel.setText("");
        txtemail.setText("");
        tgllahir.setDate(null);
        rblaki.setSelected(true);
        rbperempuan.setSelected(false);
        txttempat.setText("");
        txtnotelp.setText("");
        txtemail.setText("");
        txtareaalamat.setText("");
    }
    protected void datatable(){
        Object[] Baris = {"ID Guru", "Nama Guru", "Mata Pelajaran", "No Telepon", "E-Mail", "Jenis Kelamin", "Tempat Lahir", "Tanggal Lahir", "Alamat"};
        tabmode = new DefaultTableModel(null, Baris);
        tableguru.setModel(tabmode);
        String sql = "SELECT * FROM dataguru";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet data_guru = stat.executeQuery(sql);
            while(data_guru.next()){
                String a = data_guru.getString("id_guru");
                String b = data_guru.getString("nama_guru");
                String c = data_guru.getString("mapel");
                String d = data_guru.getString("no_telp");
                String e = data_guru.getString("email");
                String f = data_guru.getString("jk");
                String g = data_guru.getString("tempat_lahir");
                String h = data_guru.getString("tgl_lahir");
                String i = data_guru.getString("alamat");
                
                String[] data = {a, b, c, d, e, f, g, h, i};
                tabmode.addRow(data);
                }
            } catch (Exception e){
            }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtidguru = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txtmapel = new javax.swing.JTextField();
        txtnotelp = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        rblaki = new javax.swing.JRadioButton();
        rbperempuan = new javax.swing.JRadioButton();
        txttempat = new javax.swing.JTextField();
        tgllahir = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtareaalamat = new javax.swing.JTextArea();
        btnsimpan = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btnbersihkan = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableguru = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel1.setText("Data Guru SMK WALISONGO");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setText("ID Guru");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setText("Nama Guru");

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setText("Mata Pelajaran");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel5.setText("No Telepon");

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setText("Email");

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel7.setText("Jenis Kelamin");

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel8.setText("Tempat Lahir");

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel9.setText("Tanggal Lahir");

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel10.setText("Alamat");

        txtidguru.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N

        txtnama.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N

        txtmapel.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N

        txtnotelp.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N

        txtemail.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N

        rblaki.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        rblaki.setText("Laki-laki");
        rblaki.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rblakiMouseClicked(evt);
            }
        });

        rbperempuan.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        rbperempuan.setText("Perempuan");
        rbperempuan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbperempuanMouseClicked(evt);
            }
        });

        txttempat.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N

        tgllahir.setDateFormatString("yyyy-MM-dd");
        tgllahir.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N

        txtareaalamat.setColumns(20);
        txtareaalamat.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        txtareaalamat.setRows(5);
        jScrollPane1.setViewportView(txtareaalamat);

        btnsimpan.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnedit.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnedit.setText("Edit");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnbersihkan.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnbersihkan.setText("Bersihkan");
        btnbersihkan.setToolTipText("");
        btnbersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbersihkanActionPerformed(evt);
            }
        });

        btnhapus.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        tableguru.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        tableguru.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9"
            }
        ));
        tableguru.setRowHeight(25);
        tableguru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableguruMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableguru);

        jMenu1.setText("Data Siswa");
        jMenu1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jMenu1.setMargin(new java.awt.Insets(0, 5, 0, 5));
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Data Buku");
        jMenu2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jMenu2.setMargin(new java.awt.Insets(0, 5, 0, 5));
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Data Guru");
        jMenu3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jMenu3.setMargin(new java.awt.Insets(0, 5, 0, 5));
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Biaya");
        jMenu4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jMenu4.setMargin(new java.awt.Insets(0, 5, 0, 5));

        jMenuItem4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jMenuItem4.setText("Biaya SPP");
        jMenuItem4.setMargin(new java.awt.Insets(4, 0, 4, 0));
        jMenu4.add(jMenuItem4);

        jMenuItem3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jMenuItem3.setText("Biaya Buku");
        jMenuItem3.setMargin(new java.awt.Insets(4, 0, 4, 0));
        jMenu4.add(jMenuItem3);

        jMenuItem2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jMenuItem2.setText("Biaya Seragam");
        jMenuItem2.setMargin(new java.awt.Insets(4, 0, 4, 0));
        jMenu4.add(jMenuItem2);

        jMenuItem1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jMenuItem1.setText("Biaya Gedung");
        jMenuItem1.setMargin(new java.awt.Insets(4, 0, 4, 0));
        jMenu4.add(jMenuItem1);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Transaksi");
        jMenu5.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jMenu5.setMargin(new java.awt.Insets(0, 5, 0, 5));
        jMenuBar1.add(jMenu5);

        jMenu6.setText("Laporan");
        jMenu6.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jMenu6.setMargin(new java.awt.Insets(0, 5, 0, 5));
        jMenuBar1.add(jMenu6);

        jMenu7.setText("Data Admin TU");
        jMenu7.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jMenu7.setMargin(new java.awt.Insets(0, 5, 0, 5));
        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnbersihkan, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rblaki)
                                        .addGap(36, 36, 36)
                                        .addComponent(rbperempuan))
                                    .addComponent(txtidguru, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtnama)
                                    .addComponent(txtmapel)
                                    .addComponent(txtnotelp, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtemail)
                                    .addComponent(txttempat, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tgllahir, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
                                .addGap(239, 239, 239)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 944, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtidguru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtmapel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtnotelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(rblaki)
                            .addComponent(rbperempuan))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txttempat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(tgllahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbersihkan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        String sql = "INSERT INTO dataguru VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, txtidguru.getText());
            stat.setString(2, txtnama.getText());
            stat.setString(3, txtmapel.getText());
            stat.setString(4, txtnotelp.getText());
            stat.setString(5, txtemail.getText());
            
            String jeniskelamin="";
            if(rblaki.isSelected()) jeniskelamin="Laki-laki";
            else jeniskelamin="Perempuan";
            stat.setString(6, jeniskelamin);
            
            stat.setString(7, txttempat.getText());
            
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date = sdf.format(tgllahir.getDate());
            stat.setString(8, date);
            
           
            stat.setString(9, txtareaalamat.getText());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Guru Berhasil Disimpan");
            kosong();
            txtidguru.requestFocus();
            datatable();
            
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Guru Gagal Disimpan"+e);
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void rblakiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rblakiMouseClicked
        // TODO add your handling code here:
        if(rblaki.isSelected())
            rbperempuan.setSelected(false);
    }//GEN-LAST:event_rblakiMouseClicked

    private void rbperempuanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbperempuanMouseClicked
        // TODO add your handling code here:
        if(rbperempuan.isSelected())
            rblaki.setSelected(false);
    }//GEN-LAST:event_rbperempuanMouseClicked

    private void tableguruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableguruMouseClicked
        // TODO add your handling code here:
        try {
            int bar = tableguru.getSelectedRow();
            String a = tabmode.getValueAt(bar, 0).toString();
            String b = tabmode.getValueAt(bar, 1).toString();
            String c = tabmode.getValueAt(bar, 2).toString();
            String d = tabmode.getValueAt(bar, 3).toString();
            String e = tabmode.getValueAt(bar, 4).toString();
            String f = tabmode.getValueAt(bar, 5).toString();
            String g = tabmode.getValueAt(bar, 6).toString();

            java.util.Date h = new SimpleDateFormat("yyyy-MM-dd").parse((String)tabmode.getValueAt(bar, 7));
            String i = tabmode.getValueAt(bar, 8).toString();

            txtidguru.setText(a);
            txtnama.setText(b);
            txtmapel.setText(c);
            txtnotelp.setText(d);
            txtemail.setText(e);
            
            if(f.equals("Laki-laki")) {
                rblaki.setSelected(true); 
                rbperempuan.setSelected(false);
            } else {
                rblaki.setSelected(false); 
                rbperempuan.setSelected(true);
            }
            
            txttempat.setText(g);
            tgllahir.setDate(h);
            txtareaalamat.setText(i);
        
        } catch (ParseException ex) {
            Logger.getLogger(formadmintu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tableguruMouseClicked

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "UPDATE dataguru SET nama_guru=?, mapel=?, no_telp=?, email=?, jk=?, tempat_lahir=?, tgl_lahir=?, alamat=? WHERE id_guru=?";
            PreparedStatement stat = conn.prepareStatement(sql);
            
            stat.setString(1, txtnama.getText());
            stat.setString(2, txtmapel.getText());
            stat.setString(3, txtnotelp.getText());
            stat.setString(4, txtemail.getText());
            
            String jeniskelamin="";
            if(rblaki.isSelected()) jeniskelamin = "Laki-laki";
            else jeniskelamin = "Perempuan";
            stat.setString(5, jeniskelamin);
            
            stat.setString(6, txttempat.getText());
            
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date = sdf.format(tgllahir.getDate());
            stat.setString(7, date);
            
            stat.setString(8, txtareaalamat.getText());
            stat.setString(9, txtidguru.getText());
            
            stat.executeUpdate();
            txtidguru.requestFocus();
            JOptionPane.showMessageDialog(null, "Data Guru Berhasil Diubah");
            kosong();
            datatable();
            
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Guru Gagal Diubah"+e);
        }
    }//GEN-LAST:event_btneditActionPerformed

    private void btnbersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbersihkanActionPerformed
        // TODO add your handling code here:
        kosong();
    }//GEN-LAST:event_btnbersihkanActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null,"hapus","Konfirmasi Dialog", JOptionPane.YES_NO_CANCEL_OPTION);
        if (ok==0){
            String sql = "DELETE FROM dataguru WHERE id_guru ='"+txtidguru.getText()+"'";
            try{
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Guru berhasil dihapus");
                kosong();
                txtidguru.requestFocus();
                datatable();
                
            }catch (SQLException e){
                JOptionPane.showMessageDialog(null, "Data Guru gagal dihapus" +e);
            }
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formdataguru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formdataguru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formdataguru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formdataguru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formdataguru().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbersihkan;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rblaki;
    private javax.swing.JRadioButton rbperempuan;
    private javax.swing.JTable tableguru;
    private com.toedter.calendar.JDateChooser tgllahir;
    private javax.swing.JTextArea txtareaalamat;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtidguru;
    private javax.swing.JTextField txtmapel;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnotelp;
    private javax.swing.JTextField txttempat;
    // End of variables declaration//GEN-END:variables
}
