/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.JFrame;
import java.sql.ResultSet;
import com.toedter.calendar.JDateChooser;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
/**
 *
 * @author user
 */
public class seragam extends javax.swing.JFrame {
    private Connection conn = new koneksi().connect();
    private JDateChooser chooser;
    private DefaultTableModel tabmode;
    /**
     * Creates new form perlengkapan
     */
    public seragam() {
        initComponents();
        datatable();
        rng_kode();
    }
    protected void aktif() {
        txtnis.setEnabled(true);
        txtkp.setEnabled(true);
        txtharga.setEnabled(true);
        cbxadmin.setEnabled(true);
    }
    protected void kosong() {
        txtkp.setText("");
        txtnis.setText("");
        tglpem.setDate(null);
        cbxjs.setSelectedIndex(0);
        txtharga.setText("");
        cbxadmin.setSelectedIndex(0);
    }
    protected void datatable(){
        Object[] Baris ={"Kode Pembayaran", "NIS", "Tanggal Pembayaran", "Jenis Seragam", "Harga", "namaadmin"};
        tabmode = new DefaultTableModel(null, Baris);
        tabelseragam.setModel(tabmode);
        String sql = "select * from seragam";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String a = hasil.getString("kodepembayaran");
                String b = hasil.getString("nis");
                String c = hasil.getString("tglpembayaran");
                String d = hasil.getString("jenisseragam");
                String e = hasil.getString("harga");
                String f = hasil.getString("namaadmin");
                
                String[] data={a,b,c,d,e,f};
                tabmode.addRow(data);
                }
            } catch (Exception e){
            }
        
    }
    public void rng_kode() {
        int awal, akhir, hasil;
        Random rng = new Random();
        awal = 10000;
        akhir = 100000;
        hasil = rng.nextInt(akhir-awal)+awal;
        
        txtkp.setText(String.valueOf("SRG"+hasil));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        waradmin = new javax.swing.JLabel();
        warnis = new javax.swing.JLabel();
        txtnis = new javax.swing.JTextField();
        warkp = new javax.swing.JLabel();
        txtkp = new javax.swing.JTextField();
        wartglpem = new javax.swing.JLabel();
        tglpem = new com.toedter.calendar.JDateChooser();
        warjs = new javax.swing.JLabel();
        cbxjs = new javax.swing.JComboBox<>();
        txtharga = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelseragam = new javax.swing.JTable();
        btnsimpan = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btnbersihkan = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btncari = new javax.swing.JButton();
        txtcari = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbxadmin = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("Pembayaran Seragam");

        waradmin.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        waradmin.setText("Nama Admin");

        warnis.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        warnis.setText("NIS");

        txtnis.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        txtnis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnisKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnisKeyTyped(evt);
            }
        });

        warkp.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        warkp.setText("Kode Pembayaran");

        txtkp.setEditable(false);
        txtkp.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N

        wartglpem.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        wartglpem.setText("Tanggal Pembayaran");

        tglpem.setDateFormatString("yyyy-MM-dd");
        tglpem.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N

        warjs.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        warjs.setText("Jenis Seragam");

        cbxjs.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        cbxjs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Olahraga", "Batik", "Baju Muslim", "Topi dan Dasi", "Aksesoris Set Pramuka" }));

        txtharga.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        txtharga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txthargaKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel7.setText("Rp.");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        tabelseragam.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        tabelseragam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        tabelseragam.setRowHeight(25);
        tabelseragam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelseragamMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelseragam);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 898, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnsimpan.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnsimpan.setText("SIMPAN");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnedit.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnedit.setText("EDIT");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnbersihkan.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnbersihkan.setText("BERSIHKAN");
        btnbersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbersihkanActionPerformed(evt);
            }
        });

        btnhapus.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnhapus.setText("HAPUS");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btncari.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btncari.setText("Cari");
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });

        txtcari.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        txtcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcariActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setText("Biaya Seragam");

        cbxadmin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Andri Pratama", "Waskito Adhy P", "Salza Silviastanti", "Sifa Maskury", "Sonia Agustina D.M", "Dwiki Charisma I", "Fajar Hidayatullah", "Zen Fanny P.P" }));

        jMenu1.setText("Data SIswa");
        jMenu1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jMenu1.setMargin(new java.awt.Insets(0, 5, 0, 5));
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Data Buku");
        jMenu2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jMenu2.setMargin(new java.awt.Insets(0, 5, 0, 5));
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Data Guru");
        jMenu3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jMenu3.setMargin(new java.awt.Insets(0, 5, 0, 5));
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Biaya");
        jMenu4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jMenu4.setMargin(new java.awt.Insets(0, 5, 0, 5));

        jMenuItem2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jMenuItem2.setText("Biaya SPP");
        jMenuItem2.setMargin(new java.awt.Insets(4, 0, 4, 0));
        jMenu4.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jMenuItem3.setText("Biaya Buku");
        jMenuItem3.setMargin(new java.awt.Insets(4, 0, 4, 0));
        jMenu4.add(jMenuItem3);

        jMenuItem4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jMenuItem4.setText("Biaya Seragam");
        jMenuItem4.setMargin(new java.awt.Insets(4, 0, 4, 0));
        jMenu4.add(jMenuItem4);

        jMenuItem1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jMenuItem1.setText("Biaya Gedung");
        jMenuItem1.setMargin(new java.awt.Insets(4, 0, 4, 0));
        jMenu4.add(jMenuItem1);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Transaksi");
        jMenu5.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jMenu5.setMargin(new java.awt.Insets(0, 5, 0, 5));
        jMenuBar1.add(jMenu5);

        jMenu6.setText("Laporan");
        jMenu6.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jMenu6.setMargin(new java.awt.Insets(0, 5, 0, 5));
        jMenuBar1.add(jMenu6);

        jMenu7.setText("Data admin TU");
        jMenu7.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jMenu7.setMargin(new java.awt.Insets(0, 5, 0, 5));
        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(warnis)
                                    .addComponent(wartglpem)
                                    .addComponent(warjs)
                                    .addComponent(jLabel2)
                                    .addComponent(waradmin))
                                .addGap(115, 115, 115)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtnis, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtharga, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(cbxjs, javax.swing.GroupLayout.Alignment.LEADING, 0, 1, Short.MAX_VALUE)
                                        .addComponent(tglpem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cbxadmin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtkp, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btncari))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(warkp)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnbersihkan, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btncari))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(warkp)
                            .addComponent(txtkp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(warnis)
                            .addComponent(txtnis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(wartglpem)
                            .addComponent(tglpem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(warjs)
                            .addComponent(cbxjs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(waradmin)
                            .addComponent(cbxadmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbersihkan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcariActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        String sql = "INSERT INTO seragam VALUES (?, ?, ?, ?, ?, ?)";
        
        try {
            PreparedStatement seragam = conn.prepareStatement(sql);
            seragam.setString(1, txtkp.getText());
            seragam.setString(2, txtnis.getText());
            
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date = sdf.format(tglpem.getDate());
            seragam.setString(3, date);
            
            seragam.setString(4, cbxjs.getSelectedItem().toString());
            seragam.setString(5, txtharga.getText());
            seragam.setString(6, cbxadmin.getSelectedItem().toString());
            
            seragam.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Seragam Berhasil Disimpan");
            kosong();
            txtnis.requestFocus();
            datatable();
            rng_kode();
            
            } catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Data Seragam Gagal Disimpan" +e);
        }
        
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnbersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbersihkanActionPerformed
        // TODO add your handling code here:
         kosong();
         rng_kode();
    }//GEN-LAST:event_btnbersihkanActionPerformed

    private void txtnisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnisKeyTyped
        // TODO add your handling code here:
        char nis = evt.getKeyChar();
            if(!Character.isDigit(nis)||(nis == KeyEvent.VK_BACK_SPACE|| nis == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtnisKeyTyped

    private void txtnisKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnisKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtnisKeyReleased

    private void tabelseragamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelseragamMouseClicked
        // TODO add your handling code here:
        try {
            tabmode = (DefaultTableModel)tabelseragam.getModel();
            int bar = tabelseragam.getSelectedRow();
            String a = tabmode.getValueAt(bar, 0).toString();
            String b = tabmode.getValueAt(bar, 1).toString();

            java.util.Date c = new SimpleDateFormat("yyyy-MM-dd").parse((String)tabmode.getValueAt(bar, 2));
            String d = tabmode.getValueAt(bar, 3).toString();
            String e = tabmode.getValueAt(bar, 4).toString();
            String f = tabmode.getValueAt(bar, 5).toString();

            txtkp.setText(a);
            txtnis.setText(b);
            tglpem.setDate(c);
            cbxjs.setSelectedItem(d);
            txtharga.setText(e);
            cbxadmin.setSelectedItem(f);

        } catch (ParseException ex) {
            Logger.getLogger(seragam.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_tabelseragamMouseClicked

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null, "Hapus Data Seragam ?", "Menghapus Data", JOptionPane.YES_NO_CANCEL_OPTION);
        if (ok == 0 ) {
            String sql = "DELETE FROM seragam WHERE nis='"+txtnis.getText()+"'";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Pembayaran Seragam Dihapus");
                kosong();
                rng_kode();
                txtnis.requestFocus();
                datatable();
                
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Data Pembayaran Seragam Gagal Dihapus");
            }
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        try {
           String sql = "UPDATE seragam SET nis=?, tglpembayaran=?, jenisseragam=?, harga=?, namaadmin=? WHERE kodepembayaran=?";
           PreparedStatement stat= conn.prepareStatement(sql);
        
           stat.setString(1, txtnis.getText());
           
           SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
           String date = sdf.format(tglpem.getDate());
           stat.setString(2, date);
           
           stat.setString(3, cbxjs.getSelectedItem().toString());
           stat.setString(4, txtharga.getText());
           stat.setString(5, cbxadmin.getSelectedItem().toString());
           stat.setString(6, txtkp.getText());
           
           stat.executeUpdate();
           JOptionPane.showMessageDialog(null,"Data Seragamm Berhasil Diubah");
           kosong();
           txtnis.requestFocus();
           datatable();
           rng_kode();
           
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null,"Data Seragam Gagal Diubah"+e);
        }
    }//GEN-LAST:event_btneditActionPerformed

    private void txthargaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthargaKeyTyped
        // TODO add your handling code here:
        char biaya = evt.getKeyChar();
            if(!Character.isDigit(biaya)||(biaya == KeyEvent.VK_BACK_SPACE|| biaya == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_txthargaKeyTyped

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
        // TODO add your handling code here:
        Object[] Baris ={"Kode Pembayaran", "NIS", "Tanggal Pembayaran", "Jenis Seragam", "Harga", "namaadmin"};
        tabmode = new DefaultTableModel(null, Baris);
        tabelseragam.setModel(tabmode);
        String sql = "SELECT * FROM seragam WHERE kodepembayaran LIKE '%"+txtcari.getText()+"%' OR nis LIKE '%"+txtcari.getText()+"%' OR jenisseragam LIKE '%"+txtcari.getText()+"%' OR namaadmin LIKE'%"+txtcari.getText()+"%'";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()) {
                String a = hasil.getString("kodepembayaran");
                String b = hasil.getString("nis");
                String c = hasil.getString("tglpembayaran");
                String d = hasil.getString("jenisseragam");
                String e = hasil.getString("harga");
                String f = hasil.getString("namaadmin");
                
                String[] data = {a, b, c, d, e, f};
                tabmode.addRow(data);
            }
        } catch (Exception e) {
            
        }
        
    }//GEN-LAST:event_btncariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(seragam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(seragam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(seragam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(seragam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new seragam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbersihkan;
    private javax.swing.JButton btncari;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JComboBox<String> cbxadmin;
    private javax.swing.JComboBox<String> cbxjs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelseragam;
    private com.toedter.calendar.JDateChooser tglpem;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtkp;
    private javax.swing.JTextField txtnis;
    private javax.swing.JLabel waradmin;
    private javax.swing.JLabel warjs;
    private javax.swing.JLabel warkp;
    private javax.swing.JLabel warnis;
    private javax.swing.JLabel wartglpem;
    // End of variables declaration//GEN-END:variables
}
